### PR TITLE
Add readme for MixedEvent maker in StRoot/StPicoMixedEventMaker/

### PR DESCRIPTION
**Pull request by mlomnitz**

### CODE REVIEW

**Comment by jthaeder** [comment]
we should add the dependencies to compile in a more central place …

I was just hit by it myself

cheers
   Jochen

--
Dr. Jochen Thaeder
jochen@thaeder.de

Nuclear Science Division
Lawrence Berkeley National Laboratory
1 Cyclotron Road
Berkeley, CA, 94720
U.S.A.

**Comment by MustafaMustafa** [comment]
I think every package has it is own dependencies. You don't need to compile
everything if one just want to use one of them.
But, please feel free to create one. This is also related to creating a
nightly build for testing.

--Mustafa

**Comment by plexoos** [comment]
If there is interest I could help creating a .travis.yml script for continuous integration. Here is an example from one of my projects

https://github.com/plexoos/star-sti-tools/blob/master/.travis.yml

On every push the code is built using travis-ci.org services and notifications are sent by email. Here is the web interface to the build history:

https://travis-ci.org/plexoos/star-sti-tools/builds

I currently choose the same compiler and ROOT version as on RCF but that can be easily changed.

Another example to compile the Sti codes:

https://github.com/star-bnl/star-sti/blob/master/.travis.yml

Anyway, it is doable

**Comment by MustafaMustafa** [comment]
Hi Dmitri,

Thank you for the helpful examples. I was planning to look into this ticket
after QM, we view it is an important improvement but not urgent.
We are trying to make it and time is not on our sides :-)


--Mustafa

**Pull request merged**
