### PR TITLE
Introduce consistency in included headers/dependencies

### PR DESCRIPTION
**Pull request by plexoos**
The module name in the path of an included header helps to identify the origin of the file and avoids the need for additional -Ipath_to_module compiler options

### CODE REVIEW

**Comment by MustafaMustafa** [comment]
Hi @jthaeder, I was wondering if you can review these changes and merge the pull request?

Thanks,

**Comment by jthaeder** [comment]
ok, I will do so

**Comment by jthaeder** [comment]
Hi Dimitry,

Thanks a lot for the clean up!!

cheers
   Jochen

**Comment by plexoos** [comment]
Thanks!

**Pull request merged**
