### PR TITLE
code updates following last meeting

### PR DESCRIPTION
**Pull request by kunsuoh**
As we discussed last day, I modified codes and add QA histogram plotting and AnaMaker template codes.
I tested the code with very small sample, it works well.

### CODE REVIEW

**Comment by jthaeder** [comment]
Hi Kunsu,

I will remove some base functionality for bad runs event and track cuts from StHFcuts to a base class. It would be good if you can use it then in order to avoid code duplication.

Cheers
   Jochen

**Comment by MustafaMustafa** [comment]
Thank you @jthaeder for the reminder. Yes, we should all use StHFCuts once its refactored. @kunsuoh, I will contact you about that in due time. 

@kunsuoh, I will review your pull request soon.

**Comment by MustafaMustafa** [comment]
Hello @kunsuoh, 
This is very nice progress in a night. Thank you for all the work. 

I have one minor comment. We cannot display the QA at NERSC because it is public. We have to use protected area at RCF. See http://www.star.bnl.gov/protected/heavy/mstftsm/run14/picoD0ProductionMonitor/

Can you change that? Once that is changed I will merge the pull request.

**Comment by kunsuoh** [comment]
Thank you for your comments. 
I don't have permission at heavy flavour directory in protected area (there is no my directory..). I will request a permission soon. I remove web page uploading code and unprotected QA plots.

**Comment by MustafaMustafa** [comment]
Code reviewed today. Thanks to @kunsuoh  for the fast turnaround.

**Pull request merged**
